# Generated by Django 5.0.2 on 2026-03-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Вместимость (чел.)'),
        ),
    ]
