services:
  teamcity-server:
    image: jetbrains/teamcity-server:2025.11.3
    ports:
      - "8111:8111"
    volumes:
      - teamcity_data:/data/teamcity_server/datadir
      - teamcity_logs:/opt/teamcity/logs
    restart: unless-stopped

  teamcity-agent:
    build:
      context: .
      dockerfile: ci/agent.Dockerfile
    user: root
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - DOCKER_IN_DOCKER=start
      - GIT_CONFIG_COUNT=1
      - GIT_CONFIG_KEY_0=safe.directory
      - GIT_CONFIG_VALUE_0=*
    privileged: true
    volumes:
      - teamcity_agent_conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - teamcity-server
    restart: unless-stopped

  teamcity-agent-stage:
    build:
      context: .
      dockerfile: ci/agent.Dockerfile
    user: root
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - DOCKER_IN_DOCKER=start
      - GIT_CONFIG_COUNT=1
      - GIT_CONFIG_KEY_0=safe.directory
      - GIT_CONFIG_VALUE_0=*
    privileged: true
    volumes:
      - teamcity_agent_stage_conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - teamcity-server
    restart: unless-stopped

volumes:
  teamcity_data:
  teamcity_logs:
  teamcity_agent_conf:
  teamcity_agent_stage_conf:
